WITH PERIODO AS (
    SELECT 
		0	AS N

    UNION ALL

    SELECT 
		N + 1
    FROM 
		PERIODO
    WHERE 
		N < 13
) 
, MESES AS (
	SELECT 
		EOMONTH(DATEADD(MONTH, -n, GETDATE())) AS ULTIMODIAMES
	FROM 
		PERIODO
)
SELECT
	SUM(ISNULL(B.QUANTIDADE * B.CUSTO,0)) AS VALOR_ESTOQUE
	,A.ULTIMODIAMES					      AS ULTIMODIAMES
FROM 
	MESES	AS A
INNER JOIN 
	ESTOQUE AS B ON A.ULTIMODIAMES = B.DATA
GROUP BY 
	A.ULTIMODIAMES
OPTION 
	(MAXRECURSION 13); -- limita para não passar de 13 recursões
